# Kubernetes version
kube_version: v1.29.1

# Cloud Provider Configuration
cloud_provider: external
external_cloud_provider: hcloud
external_hcloud_cloud:
  token_secret_name: hcloud
  with_networks: true
  service_account_name: hcloud-cloud-controller-manager
  controller_image_tag: v1.18.0

# Network Plugin Configuration
kube_network_plugin: calico
calico_cni_name: calico
calico_felix_prometheusmetricsenabled: true

# Network Configuration
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

# Calico Configuration
calico_datastore: "kdd"
calico_pool_cidr: "10.233.64.0/18"
calico_pool_blocksize: 26
calico_cni_pool_cidr: "10.233.64.0/18"

# Cluster Configuration
cluster_name: staging-k8s-cluster
kube_proxy_strict_arp: true

# Feature Gates
kube_feature_gates:
  - "CSIMigration=true"
  - "CSIMigrationOpenStack=true"

# Additional settings for Hetzner
kubelet_config_extra_args:
  cloud-provider: external

kube_controller_manager_bind_address: 0.0.0.0
kube_scheduler_bind_address: 0.0.0.0
kube_apiserver_bind_address: 0.0.0.0

# Storage
local_path_provisioner_enabled: true
local_path_provisioner_namespace: kube-system
local_path_provisioner_storage_class: local-path
local_path_provisioner_reclaim_policy: Delete

# Ingress
ingress_nginx_enabled: true
ingress_nginx_host_network: true