---
- name: Create SSH keys for {{ environment | default('unknown') }} environment team
  hetzner.hcloud.ssh_key:
    api_token: "{{ hcloud_api_token }}"
    name: "{{ item.name }}"
    public_key: "{{ item.public_key }}"
    state: present
  loop: "{{ team_ssh_keys }}"
  when: item.public_key is defined and item.public_key != ""
  register: ssh_keys_result

- name: Display SSH keys information
  debug:
    msg: "SSH key '{{ item.hcloud_ssh_key.name }}' created/updated (ID: {{ item.hcloud_ssh_key.id }})"
  loop: "{{ ssh_keys_result.results }}"
  when: item is not skipped
  loop_control:
    label: "{{ item.hcloud_ssh_key.name }}"