---
all:
  children:
    infrastructure:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    # These groups will be populated after infrastructure is created
    kubernetes_masters:
      hosts: {}

    kubernetes_workers:
      hosts: {}

  vars:
    environment: production
    hcloud_api_token: "{{ lookup('env', 'HCLOUD_API_TOKEN_PRODUCTION') }}"